# .github/workflows/pages-with-crisp.yml
name: Build & Deploy Next.js → GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build & Export static HTML
      run: |
        npm run build
        npm run export -o docs

    - name: Disable Jekyll
      run: |
        # Ensure docs/ exists, then create .nojekyll
        mkdir -p docs
        touch docs/.nojekyll

    - name: Inject Crisp Chat snippet
      run: |
        CRISP_ID="${{ secrets.NEXT_PUBLIC_CRISP_WEBSITE_ID }}"
        find docs -type f -name '*.html' -exec sed -i \
          "/<head>/a <script>window.\$crisp=[];window.CRISP_WEBSITE_ID='${CRISP_ID}';(function(){var d=document,s=d.createElement('script');s.src='https://client.crisp.chat/l.js';s.async=1;d.getElementsByTagName('head')[0].appendChild(s);})();</script>" \
          {} +

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: docs
